In [1]:
# import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# import data
path = r'/Users/azadehrezaei/Desktop/NAEP Results Analysis'
df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'states_all_extended.csv'), index_col = False)

In [3]:
df.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,G08_HI_A_READING,G08_HI_A_MATHEMATICS,G08_AS_A_READING,G08_AS_A_MATHEMATICS,G08_AM_A_READING,G08_AM_A_MATHEMATICS,G08_HP_A_READING,G08_HP_A_MATHEMATICS,G08_TR_A_READING,G08_TR_A_MATHEMATICS
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# the dimensions of my target dataset
df.shape

(1715, 266)

In [5]:
# columns and data types
df.dtypes

PRIMARY_KEY              object
STATE                    object
YEAR                      int64
ENROLL                  float64
TOTAL_REVENUE           float64
                         ...
G08_AM_A_MATHEMATICS    float64
G08_HP_A_READING        float64
G08_HP_A_MATHEMATICS    float64
G08_TR_A_READING        float64
G08_TR_A_MATHEMATICS    float64
Length: 266, dtype: object

In [6]:
# columns/titles
df.columns

Index(['PRIMARY_KEY', 'STATE', 'YEAR', 'ENROLL', 'TOTAL_REVENUE',
       'FEDERAL_REVENUE', 'STATE_REVENUE', 'LOCAL_REVENUE',
       'TOTAL_EXPENDITURE', 'INSTRUCTION_EXPENDITURE',
       ...
       'G08_HI_A_READING', 'G08_HI_A_MATHEMATICS', 'G08_AS_A_READING',
       'G08_AS_A_MATHEMATICS', 'G08_AM_A_READING', 'G08_AM_A_MATHEMATICS',
       'G08_HP_A_READING', 'G08_HP_A_MATHEMATICS', 'G08_TR_A_READING',
       'G08_TR_A_MATHEMATICS'],
      dtype='object', length=266)

In [7]:
# selecting certain columns from the dataset
var_list = ["PRIMARY_KEY", "STATE","YEAR","ENROLL","TOTAL_REVENUE","FEDERAL_REVENUE","STATE_REVENUE", "LOCAL_REVENUE","TOTAL_EXPENDITURE","INSTRUCTION_EXPENDITURE","SUPPORT_SERVICES_EXPENDITURE","OTHER_EXPENDITURE","CAPITAL_OUTLAY_EXPENDITURE","A_A_A","G01_A_A","G02_A_A","G03_A_A","G04_A_A","G05_A_A","G06_A_A","G07_A_A","G08_A_A","G09_A_A","G10_A_A","G11_A_A","G12_A_A","KG_A_A","PK_A_A","G04_A_A_READING","G04_A_A_MATHEMATICS","G04_A_M_READING","G04_A_M_MATHEMATICS","G04_A_F_READING","G04_A_F_MATHEMATICS","G04_WH_A_READING","G04_WH_A_MATHEMATICS","G04_BL_A_READING","G04_BL_A_MATHEMATICS","G04_HI_A_READING","G04_HI_A_MATHEMATICS","G04_AS_A_READING","G04_AS_A_MATHEMATICS","G04_AM_A_READING","G04_AM_A_MATHEMATICS","G04_HP_A_READING","G04_HP_A_MATHEMATICS","G04_TR_A_READING","G04_TR_A_MATHEMATICS","G08_A_A_READING","G08_A_A_MATHEMATICS","G08_A_M_READING","G08_A_M_MATHEMATICS","G08_A_F_READING","G08_A_F_MATHEMATICS","G08_WH_A_READING","G08_WH_A_MATHEMATICS","G08_BL_A_READING","G08_BL_A_MATHEMATICS","G08_HI_A_READING","G08_HI_A_MATHEMATICS","G08_AS_A_READING","G08_AS_A_MATHEMATICS","G08_AM_A_READING","G08_AM_A_MATHEMATICS","G08_HP_A_READING","G08_HP_A_MATHEMATICS","G08_TR_A_READING","G08_TR_A_MATHEMATICS"]

In [8]:
# create a subset of the dataframe df
df_clean = df[var_list]

In [9]:
df_clean.shape

(1715, 68)

In [10]:
df_clean.dtypes

PRIMARY_KEY              object
STATE                    object
YEAR                      int64
ENROLL                  float64
TOTAL_REVENUE           float64
                         ...
G08_AM_A_MATHEMATICS    float64
G08_HP_A_READING        float64
G08_HP_A_MATHEMATICS    float64
G08_TR_A_READING        float64
G08_TR_A_MATHEMATICS    float64
Length: 68, dtype: object

In [11]:
# Set to show all the columns
pd.set_option('display.max_rows', None)

In [12]:
# Finding the number of missing values
df_clean.isnull().sum()

PRIMARY_KEY                        0
STATE                              0
YEAR                               0
ENROLL                           491
TOTAL_REVENUE                    440
FEDERAL_REVENUE                  440
STATE_REVENUE                    440
LOCAL_REVENUE                    440
TOTAL_EXPENDITURE                440
INSTRUCTION_EXPENDITURE          440
SUPPORT_SERVICES_EXPENDITURE     440
OTHER_EXPENDITURE                491
CAPITAL_OUTLAY_EXPENDITURE       440
A_A_A                             83
G01_A_A                           83
G02_A_A                           83
G03_A_A                           83
G04_A_A                           83
G05_A_A                           83
G06_A_A                           83
G07_A_A                           83
G08_A_A                           83
G09_A_A                           83
G10_A_A                           83
G11_A_A                           83
G12_A_A                           83
KG_A_A                            83
PK_A_A                           173
G04_A_A_READING                 1065
G04_A_A_MATHEMATICS             1150
G04_A_M_READING                 1065
G04_A_M_MATHEMATICS             1150
G04_A_F_READING                 1065
G04_A_F_MATHEMATICS             1150
G04_WH_A_READING                1450
G04_WH_A_MATHEMATICS            1450
G04_BL_A_READING                1489
G04_BL_A_MATHEMATICS            1486
G04_HI_A_READING                1465
G04_HI_A_MATHEMATICS            1465
G04_AS_A_READING                1551
G04_AS_A_MATHEMATICS            1547
G04_AM_A_READING                1651
G04_AM_A_MATHEMATICS            1652
G04_HP_A_READING                1699
G04_HP_A_MATHEMATICS            1700
G04_TR_A_READING                1532
G04_TR_A_MATHEMATICS            1532
G08_A_A_READING                 1153
G08_A_A_MATHEMATICS             1113
G08_A_M_READING                 1153
G08_A_M_MATHEMATICS             1113
G08_A_F_READING                 1153
G08_A_F_MATHEMATICS             1113
G08_WH_A_READING                1450
G08_WH_A_MATHEMATICS            1450
G08_BL_A_READING                1493
G08_BL_A_MATHEMATICS            1494
G08_HI_A_READING                1469
G08_HI_A_MATHEMATICS            1467
G08_AS_A_READING                1562
G08_AS_A_MATHEMATICS            1558
G08_AM_A_READING                1654
G08_AM_A_MATHEMATICS            1655
G08_HP_A_READING                1701
G08_HP_A_MATHEMATICS            1702
G08_TR_A_READING                1574
G08_TR_A_MATHEMATICS            1570
dtype: int64

In [13]:
# Only keeping the data for the years when the NAEP was administered in grades 4 and 8 for BOTH Mathematics & Reading
df_clean = df_clean[df_clean['YEAR'].isin([2003, 2005, 2007, 2009, 2011, 2013, 2015, 2017, 2019])]

In [14]:
# Resetting the index:
df_clean = df_clean.reset_index()

In [15]:
# Deleting the old index columns:
del df_clean['index']

In [16]:
df_clean.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,G08_HI_A_READING,G08_HI_A_MATHEMATICS,G08_AS_A_READING,G08_AS_A_MATHEMATICS,G08_AM_A_READING,G08_AM_A_MATHEMATICS,G08_HP_A_READING,G08_HP_A_MATHEMATICS,G08_TR_A_READING,G08_TR_A_MATHEMATICS
0,2003_ALABAMA,ALABAMA,2003,727900.0,5196054.0,567704.0,2966981.0,1661369.0,5298932.0,2817111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003_ALASKA,ALASKA,2003,133303.0,1425948.0,259423.0,813371.0,353154.0,1610289.0,763525.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003_ARIZONA,ARIZONA,2003,875111.0,6529894.0,740579.0,2912629.0,2876686.0,6210287.0,2810907.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003_ARKANSAS,ARKANSAS,2003,450158.0,3241275.0,379947.0,2394336.0,466992.0,3242799.0,1768713.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003_CALIFORNIA,CALIFORNIA,2003,6226552.0,59815855.0,5795655.0,33617766.0,20402434.0,59749885.0,29561563.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_clean.shape

(477, 68)

In [18]:
# Finding Duplicates:
df_dups = df_clean[df_clean.duplicated()]

In [19]:
# No full duplicates in the set:
df_dups

Empty DataFrame
Columns: [PRIMARY_KEY, STATE, YEAR, ENROLL, TOTAL_REVENUE, FEDERAL_REVENUE, STATE_REVENUE, LOCAL_REVENUE, TOTAL_EXPENDITURE, INSTRUCTION_EXPENDITURE, SUPPORT_SERVICES_EXPENDITURE, OTHER_EXPENDITURE, CAPITAL_OUTLAY_EXPENDITURE, A_A_A, G01_A_A, G02_A_A, G03_A_A, G04_A_A, G05_A_A, G06_A_A, G07_A_A, G08_A_A, G09_A_A, G10_A_A, G11_A_A, G12_A_A, KG_A_A, PK_A_A, G04_A_A_READING, G04_A_A_MATHEMATICS, G04_A_M_READING, G04_A_M_MATHEMATICS, G04_A_F_READING, G04_A_F_MATHEMATICS, G04_WH_A_READING, G04_WH_A_MATHEMATICS, G04_BL_A_READING, G04_BL_A_MATHEMATICS, G04_HI_A_READING, G04_HI_A_MATHEMATICS, G04_AS_A_READING, G04_AS_A_MATHEMATICS, G04_AM_A_READING, G04_AM_A_MATHEMATICS, G04_HP_A_READING, G04_HP_A_MATHEMATICS, G04_TR_A_READING, G04_TR_A_MATHEMATICS, G08_A_A_READING, G08_A_A_MATHEMATICS, G08_A_M_READING, G08_A_M_MATHEMATICS, G08_A_F_READING, G08_A_F_MATHEMATICS, G08_WH_A_READING, G08_WH_A_MATHEMATICS, G08_BL_A_READING, G08_BL_A_MATHEMATICS, G08_HI_A_READING, G08_HI_A_MATHEMATICS, G08_AS_A_READING, G08_AS_A_MATHEMATICS, G08_AM_A_READING, G08_AM_A_MATHEMATICS, G08_HP_A_READING, G08_HP_A_MATHEMATICS, G08_TR_A_READING, G08_TR_A_MATHEMATICS]
Index: []

[0 rows x 68 columns]

In [20]:
# Basic descriptive statistical analysis:
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
YEAR,477.0,2.011000e+03,5.169399e+00,2003.0,2007.00,2011.0,2015.00,2019.0
ENROLL,357.0,9.451255e+05,1.115594e+06,44179.0,272070.00,665109.0,1028259.00,6307022.0
TOTAL_REVENUE,357.0,1.115479e+07,1.361662e+07,801008.0,2778564.00,6706922.0,12999357.00,78248042.0
FEDERAL_REVENUE,357.0,1.022119e+06,1.388952e+06,75856.0,295968.00,636436.0,1116670.00,9990221.0
STATE_REVENUE,357.0,5.121749e+06,6.367098e+06,0.0,1546600.00,3232013.0,6339782.00,42360470.0
LOCAL_REVENUE,357.0,5.010925e+06,6.368771e+06,35182.0,1013658.00,2523155.0,5903450.00,34941513.0
TOTAL_EXPENDITURE,357.0,1.126676e+07,1.388169e+07,805362.0,2708776.00,6715011.0,12757599.00,78365958.0
INSTRUCTION_EXPENDITURE,357.0,5.824046e+06,7.293471e+06,330698.0,1431522.00,3383909.0,6899346.00,41954260.0
SUPPORT_SERVICES_EXPENDITURE,357.0,3.301162e+06,3.869866e+06,239435.0,852145.00,2067538.0,3750687.00,23501848.0
OTHER_EXPENDITURE,357.0,5.025831e+05,6.018313e+05,27608.0,131177.00,356389.0,577867.00,3759373.0
CAPITAL_OUTLAY_EXPENDITURE,357.0,1.087787e+06,1.549918e+06,20070.0,248505.00,618284.0,1086722.00,10223657.0
A_A_A,408.0,9.727545e+05,1.146026e+06,69433.0,279267.75,681008.0,1087134.25,6437202.0
G01_A_A,408.0,7.322296e+04,8.620332e+04,5023.0,20731.25,53280.5,84022.50,489961.0
G02_A_A,408.0,7.242593e+04,8.560026e+04,4908.0,20261.75,51471.5,83268.50,485674.0
G03_A_A,408.0,7.269845e+04,8.576666e+04,4805.0,20224.75,51634.5,84192.50,489642.0
G04_A_A,408.0,7.243460e+04,8.544275e+04,4643.0,20271.75,50972.5,82643.50,493415.0
G05_A_A,408.0,7.248917e+04,8.553276e+04,4513.0,20304.25,49718.5,82670.50,492523.0
G06_A_A,408.0,7.274677e+04,8.553982e+04,4452.0,20534.25,50218.5,82259.75,490081.0
G07_A_A,408.0,7.331153e+04,8.617042e+04,4248.0,20514.75,50221.5,82344.75,500404.0
G08_A_A,408.0,7.327172e+04,8.592583e+04,4328.0,20664.00,50194.5,81853.75,500143.0
G09_A_A,408.0,8.016855e+04,9.484253e+04,5656.0,21923.75,54105.0,86571.00,546914.0
G10_A_A,408.0,7.452226e+04,8.811586e+04,4313.0,20680.75,48675.0,82597.50,515681.0
G11_A_A,408.0,6.905914e+04,8.207401e+04,3616.0,19262.00,44559.0,80302.75,488227.0
G12_A_A,408.0,6.649418e+04,7.929189e+04,2971.0,18481.50,42046.5,80651.00,498403.0
KG_A_A,408.0,7.202787e+04,8.619833e+04,5190.0,20977.50,52093.5,81077.50,531725.0
PK_A_A,406.0,2.382102e+04,3.552622e+04,399.0,3913.50,14318.5,29440.75,256222.0
G04_A_A_READING,477.0,2.202096e+02,6.698964e+00,188.0,216.00,221.0,225.00,237.0
G04_A_A_MATHEMATICS,477.0,2.391300e+02,6.205843e+00,205.0,236.00,240.0,243.00,253.0
G04_A_M_READING,477.0,2.167673e+02,7.020853e+00,182.0,213.00,218.0,221.00,234.0
G04_A_M_MATHEMATICS,477.0,2.400881e+02,6.472031e+00,204.0,237.00,241.0,244.00,255.0
G04_A_F_READING,477.0,2.237862e+02,6.489518e+00,195.0,220.00,225.0,228.00,239.0
G04_A_F_MATHEMATICS,477.0,2.380734e+02,6.004276e+00,206.0,235.00,239.0,242.00,253.0
G04_WH_A_READING,265.0,2.300792e+02,6.445969e+00,214.0,226.00,229.0,233.00,260.0
G04_WH_A_MATHEMATICS,265.0,2.483358e+02,5.757442e+00,232.0,245.00,248.0,251.00,276.0
G04_BL_A_READING,226.0,2.046239e+02,7.046837e+00,188.0,200.00,204.0,209.00,228.0
G04_BL_A_MATHEMATICS,229.0,2.233275e+02,5.772909e+00,211.0,219.00,224.0,227.00,241.0
G04_HI_A_READING,250.0,2.089640e+02,6.423062e+00,196.0,204.00,209.0,212.75,230.0
G04_HI_A_MATHEMATICS,250.0,2.303200e+02,5.363269e+00,218.0,226.25,230.0,234.00,246.0
G04_AS_A_READING,164.0,2.357622e+02,1.022739e+01,199.0,228.00,236.0,244.00,255.0
G04_AS_A_MATHEMATICS,168.0,2.578274e+02,8.958318e+00,227.0,252.75,258.5,264.00,275.0
G04_AM_A_READING,64.0,1.970469e+02,1.055361e+01,169.0,191.75,198.0,204.00,223.0
G04_AM_A_MATHEMATICS,63.0,2.225238e+02,6.579188e+00,208.0,218.50,222.0,227.00,238.0
G04_HP_A_READING,16.0,2.028750e+02,9.837852e+00,184.0,197.75,202.0,212.00,216.0
G04_HP_A_MATHEMATICS,15.0,2.261333e+02,6.759825e+00,212.0,222.50,226.0,230.50,236.0
G04_TR_A_READING,183.0,2.242896e+02,7.332620e+00,203.0,220.00,224.0,228.00,253.0
G04_TR_A_MATHEMATICS,183.0,2.423607e+02,6.228346e+00,228.0,238.00,242.0,247.00,259.0
G08_A_A_READING,477.0,2.638784e+02,6.517421e+00,238.0,260.00,265.0,268.00,280.0
G08_A_A_MATHEMATICS,477.0,2.812306e+02,8.011892e+00,243.0,277.00,282.0,286.00,301.0
G08_A_M_READING,477.0,2.587379e+02,6.818512e+00,230.0,254.00,260.0,263.00,276.0
G08_A_M_MATHEMATICS,477.0,2.815702e+02,8.232302e+00,242.0,277.00,283.0,287.00,301.0
G08_A_F_READING,477.0,2.691572e+02,6.429842e+00,245.0,265.00,270.0,273.00,286.0
G08_A_F_MATHEMATICS,477.0,2.808449e+02,7.875678e+00,244.0,276.00,282.0,286.00,300.0
G08_WH_A_READING,265.0,2.729321e+02,5.820802e+00,256.0,270.00,272.0,275.00,300.0
G08_WH_A_MATHEMATICS,265.0,2.917509e+02,7.164613e+00,272.0,288.00,292.0,295.00,323.0
G08_BL_A_READING,222.0,2.476486e+02,6.202683e+00,235.0,244.00,247.0,251.00,273.0
G08_BL_A_MATHEMATICS,221.0,2.604434e+02,6.480230e+00,248.0,256.00,260.0,264.00,277.0
G08_HI_A_READING,246.0,2.548455e+02,5.617077e+00,239.0,251.00,255.0,258.00,277.0
G08_HI_A_MATHEMATICS,248.0,2.699960e+02,5.992909e+00,255.0,266.00,270.0,274.00,287.0
G08_AS_A_READING,153.0,2.798039e+02,9.017570e+00,257.0,274.00,281.0,286.00,298.0
G08_AS_A_MATHEMATICS,157.0,3.068981e+02,1.103444e+01,277.0,301.00,309.0,314.00,332.0
G08_AM_A_READING,61.0,2.466885e+02,7.630074e+00,229.0,242.00,247.0,252.00,261.0
G08_AM_A_MATHEMATICS,60.0,2.610167e+02,6.652365e+00,240.0,257.75,261.0,265.00,275.0
G08_HP_A_READING,14.0,2.482857e+02,6.568322e+00,234.0,244.25,248.5,253.50,259.0
G08_HP_A_MATHEMATICS,13.0,2.648462e+02,7.861787e+00,250.0,258.00,266.0,269.00,276.0
G08_TR_A_READING,141.0,2.680851e+02,7.218517e+00,249.0,263.00,267.0,272.00,291.0
G08_TR_A_MATHEMATICS,145.0,2.840828e+02,7.684313e+00,266.0,279.00,284.0,289.00,305.0

In [21]:
# Exporting the clean dataset:
df_clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'states_all_extended_clean.csv'))