# Cleaning the NAEP Dataset

In [1]:
# import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# import data
path = r'/Users/azadehrezaei/Desktop/NAEP Results Analysis'
df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'states_all_extended.csv'), index_col = False)

In [3]:
df.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,G08_HI_A_READING,G08_HI_A_MATHEMATICS,G08_AS_A_READING,G08_AS_A_MATHEMATICS,G08_AM_A_READING,G08_AM_A_MATHEMATICS,G08_HP_A_READING,G08_HP_A_MATHEMATICS,G08_TR_A_READING,G08_TR_A_MATHEMATICS
0,1986_ALABAMA,ALABAMA,1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1986_ALASKA,ALASKA,1986,NaN,NaN,350204.0,1600503.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1986_ARIZONA,ARIZONA,1986,NaN,NaN,NaN,1600503.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1986_ARKANSAS,ARKANSAS,1986,NaN,NaN,NaN,1600503.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1986_CALIFORNIA,CALIFORNIA,1986,NaN,NaN,NaN,1600503.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# the dimensions of my target dataset
df.shape

(1715, 84)

In [5]:
# columns and data types
df.dtypes

PRIMARY_KEY              object
STATE                    object
YEAR                      int64
ENROLL                  float64
TOTAL_REVENUE           float64
                         ...
G08_AM_A_MATHEMATICS    float64
G08_HP_A_READING        float64
G08_HP_A_MATHEMATICS    float64
G08_TR_A_READING        float64
G08_TR_A_MATHEMATICS    float64
Length: 84, dtype: object

In [6]:
# columns/titles
df.columns

Index(['PRIMARY_KEY', 'STATE', 'YEAR', 'ENROLL', 'TOTAL_REVENUE',
       'FEDERAL_REVENUE', 'STATE_REVENUE', 'LOCAL_REVENUE',
       'TOTAL_EXPENDITURE', 'INSTRUCTION_EXPENDITURE',
       'SUPPORT_SERVICES_EXPENDITURE', 'OTHER_EXPENDITURE',
       'CAPITAL_OUTLAY_EXPENDITURE', 'A_A_A', 'G04_A_A', 'G08_A_A', 'G04_AM_F',
       'G04_AM_M', 'G04_AS_F', 'G04_AS_M', 'G04_BL_F', 'G04_BL_M', 'G04_HI_F',
       'G04_HI_M', 'G04_HP_F', 'G04_HP_M', 'G04_TR_F', 'G04_TR_M', 'G04_WH_F',
       'G04_WH_M', 'G08_AM_F', 'G08_AM_M', 'G08_AS_F', 'G08_AS_M', 'G08_BL_F',
       'G08_BL_M', 'G08_HI_F', 'G08_HI_M', 'G08_HP_F', 'G08_HP_M', 'G08_TR_F',
       'G08_TR_M', 'G08_WH_F', 'G08_WH_M', 'G04_A_A_READING',
       'G04_A_A_MATHEMATICS', 'G04_A_M_READING', 'G04_A_M_MATHEMATICS',
       'G04_A_F_READING', 'G04_A_F_MATHEMATICS', 'G04_WH_A_READING',
       'G04_WH_A_MATHEMATICS', 'G04_BL_A_READING', 'G04_BL_A_MATHEMATICS',
       'G04_HI_A_READING', 'G04_HI_A_MATHEMATICS', 'G04_AS_A_READING',
       'G04_AS_A_MATHEMATICS', 'G04_AM_A_READING', 'G04_AM_A_MATHEMATICS',
       'G04_HP_A_READING', 'G04_HP_A_MATHEMATICS', 'G04_TR_A_READING',
       'G04_TR_A_MATHEMATICS', 'G08_A_A_READING', 'G08_A_A_MATHEMATICS',
       'G08_A_M_READING', 'G08_A_M_MATHEMATICS', 'G08_A_F_READING',
       'G08_A_F_MATHEMATICS', 'G08_WH_A_READING', 'G08_WH_A_MATHEMATICS',
       'G08_BL_A_READING', 'G08_BL_A_MATHEMATICS', 'G08_HI_A_READING',
       'G08_HI_A_MATHEMATICS', 'G08_AS_A_READING', 'G08_AS_A_MATHEMATICS',
       'G08_AM_A_READING', 'G08_AM_A_MATHEMATICS', 'G08_HP_A_READING',
       'G08_HP_A_MATHEMATICS', 'G08_TR_A_READING', 'G08_TR_A_MATHEMATICS'],
      dtype='object')

In [7]:
# selecting certain columns from the dataset
var_list = ["PRIMARY_KEY", "STATE","YEAR","ENROLL","TOTAL_REVENUE","FEDERAL_REVENUE","STATE_REVENUE", "LOCAL_REVENUE","TOTAL_EXPENDITURE","INSTRUCTION_EXPENDITURE","SUPPORT_SERVICES_EXPENDITURE","OTHER_EXPENDITURE","CAPITAL_OUTLAY_EXPENDITURE","A_A_A","G04_A_A","G08_A_A", "G04_A_A_READING","G04_A_A_MATHEMATICS","G04_A_M_READING","G04_A_M_MATHEMATICS","G04_A_F_READING","G04_A_F_MATHEMATICS","G04_WH_A_READING","G04_WH_A_MATHEMATICS","G04_BL_A_READING","G04_BL_A_MATHEMATICS","G04_HI_A_READING","G04_HI_A_MATHEMATICS","G04_AS_A_READING","G04_AS_A_MATHEMATICS","G04_AM_A_READING","G04_AM_A_MATHEMATICS","G04_HP_A_READING","G04_HP_A_MATHEMATICS","G04_TR_A_READING","G04_TR_A_MATHEMATICS","G08_A_A_READING","G08_A_A_MATHEMATICS","G08_A_M_READING","G08_A_M_MATHEMATICS","G08_A_F_READING","G08_A_F_MATHEMATICS","G08_WH_A_READING","G08_WH_A_MATHEMATICS","G08_BL_A_READING","G08_BL_A_MATHEMATICS","G08_HI_A_READING","G08_HI_A_MATHEMATICS","G08_AS_A_READING","G08_AS_A_MATHEMATICS","G08_AM_A_READING","G08_AM_A_MATHEMATICS","G08_HP_A_READING","G08_HP_A_MATHEMATICS","G08_TR_A_READING","G08_TR_A_MATHEMATICS"]

In [8]:
# create a subset of the dataframe df
df_clean = df[var_list]

In [9]:
df_clean.shape

(1715, 56)

In [10]:
df_clean.dtypes

PRIMARY_KEY                      object
STATE                            object
YEAR                              int64
ENROLL                          float64
TOTAL_REVENUE                   float64
FEDERAL_REVENUE                 float64
STATE_REVENUE                   float64
LOCAL_REVENUE                   float64
TOTAL_EXPENDITURE               float64
INSTRUCTION_EXPENDITURE         float64
SUPPORT_SERVICES_EXPENDITURE    float64
OTHER_EXPENDITURE               float64
CAPITAL_OUTLAY_EXPENDITURE      float64
A_A_A                           float64
G04_A_A                         float64
G08_A_A                         float64
G04_A_A_READING                 float64
G04_A_A_MATHEMATICS             float64
G04_A_M_READING                 float64
G04_A_M_MATHEMATICS             float64
G04_A_F_READING                 float64
G04_A_F_MATHEMATICS             float64
G04_WH_A_READING                float64
G04_WH_A_MATHEMATICS            float64
G04_BL_A_READING                float64
G04_BL_A_MATHEMATICS            float64
G04_HI_A_READING                float64
G04_HI_A_MATHEMATICS            float64
G04_AS_A_READING                float64
G04_AS_A_MATHEMATICS            float64
G04_AM_A_READING                float64
G04_AM_A_MATHEMATICS            float64
G04_HP_A_READING                float64
G04_HP_A_MATHEMATICS            float64
G04_TR_A_READING                float64
G04_TR_A_MATHEMATICS            float64
G08_A_A_READING                 float64
G08_A_A_MATHEMATICS             float64
G08_A_M_READING                 float64
G08_A_M_MATHEMATICS             float64
G08_A_F_READING                 float64
G08_A_F_MATHEMATICS             float64
G08_WH_A_READING                float64
G08_WH_A_MATHEMATICS            float64
G08_BL_A_READING                float64
G08_BL_A_MATHEMATICS            float64
G08_HI_A_READING                float64
G08_HI_A_MATHEMATICS            float64
G08_AS_A_READING                float64
G08_AS_A_MATHEMATICS            float64
G08_AM_A_READING                float64
G08_AM_A_MATHEMATICS            float64
G08_HP_A_READING                float64
G08_HP_A_MATHEMATICS            float64
G08_TR_A_READING                float64
G08_TR_A_MATHEMATICS            float64
dtype: object

In [11]:
# Set to show all the columns
pd.set_option('display.max_rows', None)

In [12]:
# Finding the number of missing values
df_clean.isnull().sum()

PRIMARY_KEY                        0
STATE                              0
YEAR                               0
ENROLL                           389
TOTAL_REVENUE                    334
FEDERAL_REVENUE                  334
STATE_REVENUE                    272
LOCAL_REVENUE                    338
TOTAL_EXPENDITURE                334
INSTRUCTION_EXPENDITURE          338
SUPPORT_SERVICES_EXPENDITURE     298
OTHER_EXPENDITURE                389
CAPITAL_OUTLAY_EXPENDITURE       338
A_A_A                             83
G04_A_A                           83
G08_A_A                           83
G04_A_A_READING                 1065
G04_A_A_MATHEMATICS             1150
G04_A_M_READING                 1065
G04_A_M_MATHEMATICS             1150
G04_A_F_READING                 1065
G04_A_F_MATHEMATICS             1150
G04_WH_A_READING                1450
G04_WH_A_MATHEMATICS            1450
G04_BL_A_READING                1489
G04_BL_A_MATHEMATICS            1486
G04_HI_A_READING                1465
G04_HI_A_MATHEMATICS            1465
G04_AS_A_READING                1551
G04_AS_A_MATHEMATICS            1547
G04_AM_A_READING                1651
G04_AM_A_MATHEMATICS            1652
G04_HP_A_READING                1699
G04_HP_A_MATHEMATICS            1700
G04_TR_A_READING                1532
G04_TR_A_MATHEMATICS            1532
G08_A_A_READING                 1153
G08_A_A_MATHEMATICS             1113
G08_A_M_READING                 1153
G08_A_M_MATHEMATICS             1113
G08_A_F_READING                 1153
G08_A_F_MATHEMATICS             1113
G08_WH_A_READING                1450
G08_WH_A_MATHEMATICS            1450
G08_BL_A_READING                1493
G08_BL_A_MATHEMATICS            1494
G08_HI_A_READING                1469
G08_HI_A_MATHEMATICS            1467
G08_AS_A_READING                1562
G08_AS_A_MATHEMATICS            1558
G08_AM_A_READING                1654
G08_AM_A_MATHEMATICS            1655
G08_HP_A_READING                1701
G08_HP_A_MATHEMATICS            1702
G08_TR_A_READING                1574
G08_TR_A_MATHEMATICS            1570
dtype: int64

In [13]:
df_clean = df_clean.drop(df_clean[df_clean['STATE'].isin(['NATIONAL', 'DODEA'])].index)

In [14]:
# Only keeping the data for the years 2003 and after
df_clean = df_clean[df_clean['YEAR'] > 2002 ]

In [15]:
# Resetting the index:
df_clean = df_clean.reset_index()

In [16]:
# Deleting the old index columns:
del df_clean['index']

In [17]:
df_clean.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,G08_HI_A_READING,G08_HI_A_MATHEMATICS,G08_AS_A_READING,G08_AS_A_MATHEMATICS,G08_AM_A_READING,G08_AM_A_MATHEMATICS,G08_HP_A_READING,G08_HP_A_MATHEMATICS,G08_TR_A_READING,G08_TR_A_MATHEMATICS
0,2003_ALABAMA,ALABAMA,2003,727900.0,5196054.0,567704.0,2966981.0,1661369.0,5298932.0,2817111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003_ALASKA,ALASKA,2003,133303.0,1425948.0,259423.0,813371.0,353154.0,1610289.0,763525.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003_ARIZONA,ARIZONA,2003,875111.0,6529894.0,740579.0,2912629.0,2876686.0,6210287.0,2810907.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003_ARKANSAS,ARKANSAS,2003,450158.0,3241275.0,379947.0,2394336.0,466992.0,3242799.0,1768713.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003_CALIFORNIA,CALIFORNIA,2003,6226552.0,59815855.0,5795655.0,33617766.0,20402434.0,59749885.0,29561563.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_clean.shape

(816, 56)

In [19]:
# Finding Duplicates:
df_dups = df_clean[df_clean.duplicated()]

In [20]:
# No full duplicates in the set:
df_dups

Empty DataFrame
Columns: [PRIMARY_KEY, STATE, YEAR, ENROLL, TOTAL_REVENUE, FEDERAL_REVENUE, STATE_REVENUE, LOCAL_REVENUE, TOTAL_EXPENDITURE, INSTRUCTION_EXPENDITURE, SUPPORT_SERVICES_EXPENDITURE, OTHER_EXPENDITURE, CAPITAL_OUTLAY_EXPENDITURE, A_A_A, G04_A_A, G08_A_A, G04_A_A_READING, G04_A_A_MATHEMATICS, G04_A_M_READING, G04_A_M_MATHEMATICS, G04_A_F_READING, G04_A_F_MATHEMATICS, G04_WH_A_READING, G04_WH_A_MATHEMATICS, G04_BL_A_READING, G04_BL_A_MATHEMATICS, G04_HI_A_READING, G04_HI_A_MATHEMATICS, G04_AS_A_READING, G04_AS_A_MATHEMATICS, G04_AM_A_READING, G04_AM_A_MATHEMATICS, G04_HP_A_READING, G04_HP_A_MATHEMATICS, G04_TR_A_READING, G04_TR_A_MATHEMATICS, G08_A_A_READING, G08_A_A_MATHEMATICS, G08_A_M_READING, G08_A_M_MATHEMATICS, G08_A_F_READING, G08_A_F_MATHEMATICS, G08_WH_A_READING, G08_WH_A_MATHEMATICS, G08_BL_A_READING, G08_BL_A_MATHEMATICS, G08_HI_A_READING, G08_HI_A_MATHEMATICS, G08_AS_A_READING, G08_AS_A_MATHEMATICS, G08_AM_A_READING, G08_AM_A_MATHEMATICS, G08_HP_A_READING, G08_HP_A_MATHEMATICS, G08_TR_A_READING, G08_TR_A_MATHEMATICS]
Index: []

[0 rows x 56 columns]

In [21]:
# Basic descriptive statistical analysis:
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
YEAR,816.0,2.010562e+03,4.719469e+00,2003.0,2006.75,2010.5,2014.25,2019.0
ENROLL,816.0,9.461287e+05,1.116289e+06,43866.0,272895.00,665275.0,1032083.25,6307022.0
TOTAL_REVENUE,816.0,1.163714e+07,1.421730e+07,801008.0,2903026.75,7058886.0,13451722.25,96041050.0
FEDERAL_REVENUE,816.0,1.046766e+06,1.398853e+06,75856.0,302575.50,663698.5,1125001.00,9990221.0
STATE_REVENUE,816.0,5.319134e+06,6.566372e+06,0.0,1614307.25,3385343.0,6588316.00,54106131.0
LOCAL_REVENUE,816.0,5.271238e+06,6.819653e+06,35182.0,1113235.50,2688662.0,6195637.00,42207081.0
TOTAL_EXPENDITURE,816.0,1.162423e+07,1.432638e+07,805362.0,2834127.50,7069436.0,13486907.25,91636154.0
INSTRUCTION_EXPENDITURE,816.0,6.112236e+06,7.762462e+06,330698.0,1498990.75,3619988.0,7211439.75,48286842.0
SUPPORT_SERVICES_EXPENDITURE,816.0,3.467313e+06,4.113457e+06,239435.0,887408.00,2142476.5,3976820.25,29204613.0
OTHER_EXPENDITURE,816.0,5.230866e+05,6.326875e+05,27608.0,133738.00,361267.0,610655.25,4557271.0
CAPITAL_OUTLAY_EXPENDITURE,816.0,1.129286e+06,1.603686e+06,20070.0,268374.25,661958.5,1172697.25,10223657.0
A_A_A,765.0,9.730934e+05,1.146132e+06,68681.0,279873.00,681848.0,1087030.00,6441557.0
G04_A_A,765.0,7.238773e+04,8.532034e+04,4577.0,20217.00,51027.0,82862.00,493415.0
G08_A_A,765.0,7.325594e+04,8.597638e+04,4202.0,20588.00,50186.0,82021.00,500143.0
G04_A_A_READING,459.0,2.200044e+02,6.660512e+00,188.0,216.00,221.0,224.50,237.0
G04_A_A_MATHEMATICS,459.0,2.390392e+02,6.260937e+00,205.0,236.00,240.0,243.00,253.0
G04_A_M_READING,459.0,2.165556e+02,6.993343e+00,182.0,213.00,218.0,221.00,234.0
G04_A_M_MATHEMATICS,459.0,2.399891e+02,6.528230e+00,204.0,237.00,241.0,244.00,255.0
G04_A_F_READING,459.0,2.235817e+02,6.440132e+00,195.0,220.00,225.0,228.00,239.0
G04_A_F_MATHEMATICS,459.0,2.379956e+02,6.060825e+00,206.0,235.00,239.0,242.00,253.0
G04_WH_A_READING,255.0,2.299176e+02,6.484770e+00,214.0,226.00,229.0,233.00,260.0
G04_WH_A_MATHEMATICS,255.0,2.482824e+02,5.847696e+00,232.0,245.00,248.0,251.00,276.0
G04_BL_A_READING,216.0,2.041296e+02,6.455706e+00,188.0,199.00,204.0,209.00,223.0
G04_BL_A_MATHEMATICS,219.0,2.230411e+02,5.562254e+00,211.0,219.00,223.0,227.00,239.0
G04_HI_A_READING,240.0,2.085875e+02,5.916491e+00,196.0,204.00,208.0,212.00,226.0
G04_HI_A_MATHEMATICS,240.0,2.300833e+02,5.174096e+00,218.0,226.00,229.0,234.00,245.0
G04_AS_A_READING,154.0,2.356948e+02,1.052996e+01,199.0,228.00,236.0,244.00,255.0
G04_AS_A_MATHEMATICS,158.0,2.579304e+02,9.149931e+00,227.0,252.25,259.0,264.00,275.0
G04_AM_A_READING,59.0,1.964915e+02,1.080768e+01,169.0,191.00,198.0,202.00,223.0
G04_AM_A_MATHEMATICS,58.0,2.221724e+02,6.741175e+00,208.0,218.00,221.0,225.00,238.0
G04_HP_A_READING,11.0,1.980909e+02,7.942979e+00,184.0,194.50,199.0,202.00,211.0
G04_HP_A_MATHEMATICS,10.0,2.234000e+02,6.131884e+00,212.0,221.25,223.5,227.50,232.0
G04_TR_A_READING,173.0,2.239191e+02,7.301189e+00,203.0,219.00,223.0,228.00,253.0
G04_TR_A_MATHEMATICS,173.0,2.421040e+02,6.270143e+00,228.0,238.00,241.0,247.00,259.0
G08_A_A_READING,459.0,2.636514e+02,6.434797e+00,238.0,260.00,265.0,268.00,278.0
G08_A_A_MATHEMATICS,459.0,2.810784e+02,8.087563e+00,243.0,276.50,282.0,286.00,301.0
G08_A_M_READING,459.0,2.584880e+02,6.719372e+00,230.0,254.00,260.0,263.00,273.0
G08_A_M_MATHEMATICS,459.0,2.814052e+02,8.301711e+00,242.0,277.00,283.0,287.00,301.0
G08_A_F_READING,459.0,2.689434e+02,6.362851e+00,245.0,265.00,270.0,273.00,282.0
G08_A_F_MATHEMATICS,459.0,2.807124e+02,7.958138e+00,244.0,276.00,282.0,286.00,300.0
G08_WH_A_READING,255.0,2.727333e+02,5.780045e+00,256.0,270.00,272.0,275.00,300.0
G08_WH_A_MATHEMATICS,255.0,2.916275e+02,7.261593e+00,272.0,288.00,291.0,295.00,323.0
G08_BL_A_READING,212.0,2.471745e+02,5.519694e+00,235.0,243.75,247.0,251.00,261.0
G08_BL_A_MATHEMATICS,211.0,2.600900e+02,6.229457e+00,248.0,255.50,260.0,264.00,277.0
G08_HI_A_READING,236.0,2.544788e+02,5.015251e+00,239.0,251.00,254.0,258.00,266.0
G08_HI_A_MATHEMATICS,238.0,2.696891e+02,5.708455e+00,255.0,266.00,269.5,273.00,285.0
G08_AS_A_READING,143.0,2.797692e+02,9.254380e+00,257.0,273.50,281.0,286.00,298.0
G08_AS_A_MATHEMATICS,147.0,3.070340e+02,1.128122e+01,277.0,301.00,309.0,314.00,332.0
G08_AM_A_READING,56.0,2.462857e+02,7.824703e+00,229.0,241.00,246.0,251.50,261.0
G08_AM_A_MATHEMATICS,55.0,2.605636e+02,6.732353e+00,240.0,257.00,260.0,264.00,275.0
G08_HP_A_READING,9.0,2.445556e+02,4.798727e+00,234.0,243.00,245.0,248.00,250.0
G08_HP_A_MATHEMATICS,8.0,2.603750e+02,5.998512e+00,250.0,257.00,260.5,264.00,268.0
G08_TR_A_READING,131.0,2.675878e+02,7.048044e+00,249.0,262.50,267.0,272.00,291.0
G08_TR_A_MATHEMATICS,135.0,2.836963e+02,7.765475e+00,266.0,279.00,284.0,288.00,305.0

In [22]:
# Exporting the clean dataset:
df_clean.to_csv(os.path.join(path,'02 Data', 'Prepared Data', 'states_all_extended_clean.csv'))